on:
  rss:
    url: https://gitlab.com/prtmax.atom?feed_token=${{ secrets.GITLAB_FEED_TOKEN }}
    # config:
    #   limit: 15
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          id: ${{on.rss.outputs.id}}
          title: ${{on.rss.outputs.title}}
          author: ${{on.rss.outputs.author}}
          link: ${{on.rss.outputs.link}}
          summary: ${{on.rss.outputs.summary}}
          updated: ${{on.rss.outputs.updated}}
        run: |
          echo id: $id
          echo author: $author
          echo link: $link
          echo updated: $updated
          echo $summary | xq '.div.div.p'
