on:
  rss:
    url: https://gitlab.com/prtmax.atom?feed_token=${{ secrets.GITLAB_FEED_TOKEN }}
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          summary: ${{on.rss.outputs.summary}}
        run: |
          echo id: ${{on.rss.outputs.id}}
          echo title: ${{on.rss.outputs.title}}
          echo author: ${{on.rss.outputs.author}}
          echo link: ${{on.rss.outputs.link}}
          echo updated: ${{on.rss.outputs.updated}}
          echo $summary | xq '.div.div.p'

