on:
  rss:
    url: https://gitlab.com/prtmax.atom?feed_token=${{ secrets.GITLAB_FEED_TOKEN }}
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:

      - name: Setup deps
        run: |
          curl -L -o xq.tar.gz https://github.com/sibprogrammer/xq/releases/download/v1.2.5/xq_1.2.5_linux_amd64.tar.gz
          tar -zxf ./xq.tar.gz -C ./

      - uses: actions/download-artifact@v4
        with:
          name: artifact-tpl

      - name: Generate template
        env:
          title: ${{on.rss.outputs.title}}
          summary: ${{on.rss.outputs.summary}}
        run: |
          PARSED_SUMMARY=$(echo $summary | ./xq -q 'div > div > p')
          TPL_FILE=.notify.local.md

          echo ${{on.rss.outputs}}

          echo '---' >> $TPL_FILE
          echo 'author: ${{on.rss.outputs.author}}' >> $TPL_FILE
          echo 'link: ${{on.rss.outputs.link}}' >> $TPL_FILE
          echo "title: ${title}" >> $TPL_FILE
          echo '---' >> $TPL_FILE
          echo '' >> $TPL_FILE
          echo $PARSED_SUMMARY >> $TPL_FILE
          echo '' >> $TPL_FILE
          echo '' >> $TPL_FILE

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-tpl
          path: .notify.local.md

      # - uses: fewensa/actions/tepusher@main
      #   with:
      #     template: .notify.local.md
      #     token: ${{ secrets.WEPLUSBOT_TOKEN }}
      #     receiver: "#6cfbef7cc90c4d1ab0842b13e483fafb"

